# Generated by Django 4.0.3 on 2022-03-24 05:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gas_station_id', models.CharField(max_length=24, verbose_name='Identificador de Gasolinera')),
                ('address', models.TextField(verbose_name='Direccion')),
                ('rfc', models.CharField(max_length=12, verbose_name='RFC')),
                ('regular_gasoline_price', models.FloatField(blank=True, null=True, verbose_name='Precio de gasolina regular')),
                ('premium_gasoline_price', models.FloatField(blank=True, null=True, verbose_name='Precio de gasolina premium')),
                ('diesel_price', models.FloatField(blank=True, null=True, verbose_name='Precio de gasolina premium')),
                ('longitude', models.CharField(max_length=16, verbose_name='Longitud')),
                ('latitude', models.CharField(max_length=16, verbose_name='Latitud')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Codigo Postal')),
                ('company_name', models.CharField(max_length=255, verbose_name='Razon Social')),
            ],
        ),
    ]
